### ISSUE TITLE
Computed属性标签不起作用

### ISSUE THREAD

**Issue by lbx1979** [EminemJK/Banana#11]
` [Computed]
  public string TableName { get; set; }`
调用repo.QueryList发现就报错了, TableName列不存在,
这个attribute不是标记列不放到select中的吗?

**Comment by EminemJK** [comment]
Computed：计算属性，此列不作为更新，
如需要非查询非更新列，标记[Write(false)]

**Comment by lbx1979** [comment]
了解, 多谢
