### ISSUE TITLE
支持原生的TransactionScope吗

### ISSUE THREAD

**Issue by lbx1979** [EminemJK/Banana#3]
你好
是否支持TransactionScope这种方式的事务支持吗, 在里面使用repository类操作?

**Comment by EminemJK** [comment]
支持，
1、多仓储使用工作单元
`UnitOfWork`；

2、单一仓储使用
`repo.OpenTransaction()`
开启；
3、脱离仓储可以直接使用
`IDbConnection conn = ConnectionBuilder.CreateConnection()`
获取到 IDbConnection

**Comment by lbx1979** [comment]
能否处理多个连接的事务呢, 我看代码里启动的还是基于连接的事务啊, 另外就是repo里插入多行也启动里自己的事务

Lio.Huang <notifications@github.com> 于2019年3月7日周四 下午4:57写道：

**Comment by EminemJK** [comment]
1、可以直接使用原生的TransactionScope
2、之前目的是保证插入数据的完整性，下个版本可增加开关，计划和DI一起

**Comment by lbx1979** [comment]
repo把动态sql能封装起来的话更好了, 像我们的应用总是有需要写sql的场景

Lio.Huang <notifications@github.com> 于2019年3月7日周四 下午7:24写道：

**Comment by EminemJK** [comment]
可以举例描述一下你们常用到的场景吗？

**Comment by lbx1979** [comment]
我们做企业软件, 做某些保存或者删除时会去检查操作别的业务表, 做复杂关联查询, 还有就是查询列是动态拼接出来的因为在代码阶段列可能都不存在,
以前经常是用dataset操作的, 都变成实体的话还是挺麻烦的

Lio.Huang <notifications@github.com> 于2019年3月7日周四 下午9:45写道：

**Comment by EminemJK** [comment]
ORM旨在减少书写SQL进行开发，利用对象来进行对表做映射关系，主要还是便利开发。在复杂的业务开发需求中，看情况决定是否选择ORM来做数据持久层吧
