### ISSUE TITLE
PG数据库更新问题

### ISSUE THREAD

**Issue by lbx1979** [EminemJK/Banana#5]
你好, 我看了一下代码,pgsql数据库的 组织SQL分支针对字段有双引号的, 这样导致实体和数据库字段大小写必要一致才行, 原来在dapper的issues提过一直没解决

**Comment by EminemJK** [comment]
PostgreSQL 是大小写敏感的，所以还是建议区分开来

**Comment by lbx1979** [comment]
PG数据库在Sql里大小写不敏感啊,创建时如果要区分大小写得加双引号,这样查询时也得加, 挺麻烦的...

Lio.Huang <notifications@github.com> 于2019年4月9日周二 上午10:00写道：

**Comment by EminemJK** [comment]
PostgreSQL 是大小写敏感的，并默认对SQL语句转化为小写，其次不会在公共分支里做个性化修改，也有需要大写的开发者，如果需要，你可以fork分支上进行个性化修改

**Comment by lbx1979** [comment]
好的, 谢谢

Lio.Huang <notifications@github.com> 于2019年4月9日周二 上午10:18写道：
