### ISSUE TITLE
分页异常反馈

### ISSUE THREAD

**Issue by tigeryzx** [EminemJK/Banana#8]
环境
DotnetCore 2.2
Oracle 10g

你好，在开发途中发现两个问题。

1. 当表主键不叫“ID”时分页报错，查看源码得知以下问题，下面用OracleAdapter作例子

OracleAdapter 198行，当不传入分页时默认采用"ID"来排序，但表主键不一定叫ID，建议取Entity中 KeyAttribute 中标的列作默认排序列以免发生错误。
``` c#
                string orderSql = "ID";
                if (order != null)
                {
                    orderSql = SqlBuilder.GetArgsString("ORDER BY", prefix: repository.TableName, args: order);
                }
```

2. 按以下传参数调用OracleAdapter时返回的Sqlbuilder获取SQL属性时会报异常
``` c#
        private static void TestOracleAdapter()
        {
            OracleAdapter oracleAdapter = new OracleAdapter();
            var sqlbuilder = oracleAdapter.GetPageList(new Repository<UserInfo>(),
                pageNum: 1,
                pageSize: 10,
                order: "Name",
                whereString: "Name=@Name and Phone=@Phone",
                param: new { Name = "tom", Phone = "123456" });

            // 访问SQL属性时会报 System.ArgumentOutOfRangeException:“Specified argument was out of the range of valid values.
Arg_ParamName_Name
            var sql = sqlbuilder.SQL;
        }
```

以OracleAdapter为例，调试发现是这行 210 
``` c#
                sqlBuilderRows.From(repository.TableName);
                if (!string.IsNullOrEmpty(whereString))
                {
                    sqlBuilderRows.Where(whereString, param);
                }
               // sqlBuilderRows.Arguments 传入后访问sqlBuilder.SQL 则会报此异常 把参数改为 param 则正常，由于急着用没深究原因
                sqlBuilder.Append($"From ({sqlBuilderRows.SQL}) TT", sqlBuilderRows.Arguments);
````

**Comment by EminemJK** [comment]
已经更新源码，还未发布NuGet，我本地暂时无法调试oracle，但逻辑差不多。你更新后用源码调试，没问题就通知我上nuget吧
1. 已解决；
2.已解决。
注：oracle参数化语法错误，不是用@是: ，举例：
`var sqlbuilder = oracleAdapter.GetPageList(new Repository<UserInfo>(),
                pageNum: 1,
                pageSize: 10,
                order: "Name",
                whereString: "Name=:Name and Phone=:Phone",
                param: new { Name = "tom", Phone = "123456" });`

**Comment by tigeryzx** [comment]
感谢，我尝试过问题1及2都已经解决了，你提到传参数ORACLE 用:不是用@，请问有没有考虑统一参数占位符呢，毕竟你既然分了ISqlAdapter就是为了屏蔽不同类型数据库的细节，如果可以的话大可把传参点位符号统一，一些基本的SQL切换成不同数据库时就不需要变动程序里面的SQL了。

**Comment by EminemJK** [comment]
1.已发布Nuget；
2.感谢提议，但目前还不会考虑将Banana设计得那么重，因为Dapper是个轻量级ORM，暴露出的`IDBConnection`仍支持原生语法，一但我这边将IDBConnection包装成类似ISqlAdapter的方式，会导致Banana和Dapper出现两种占位符，所以得慎重考虑一下。

**Comment by tigeryzx** [comment]
OK,谢谢回复，我明白你说的，我之前是想着平时用的都封装到Repo中,至于底层用什么ORM也方便替换，实际使用时只允许经Repo来调用这样就能在这个基础的Repo中把参数占位符做替换原生占位符处理，但我忽略了Repo中暴露的IDBConnection能直接使用Dapper了，谢谢提醒。
